---

- name: "Include setup tasks"
  include: tasks-initial.yml

- name: "Include detection tasks"
  include: tasks-upsource-detect.yml

- name: "Include clean-up tasks"
  include: tasks-upsource-clean.yml
  when: '"{{ config_file.stat.exists }}" == "true" and "{{ upsource_version }}" not in "{{ upsource_installed_version.stdout_lines }}"'

- name: "Include config tasks"
  include: tasks-config.yml

- name: "Include upsource distribution tasks"
  include: tasks-upsource-distribution.yml

- name: "Include upsource service tasks"
  include: tasks-upsource-service.yml