---

- name: "Config | Create directories"
  become: yes
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: true
  with_items:
    - "{{ upsource_install_dir }}"