---

- name: "UpSource | Service | Get status"
  shell: "{{ upsource_install_dir }}/bin/upsource.sh status | cat"
  register: upsource_service_status
  changed_when: false
  tags:
    - upsource

- name: "UpSource | Service | Start"
  shell: "{{ upsource_install_dir }}/bin/upsource.sh start"
  when: '"Upsource is running" not in upsource_service_status.stdout'
  tags:
    - upsource