---

- name: "UpSource | Service | Stop"
  become: yes
  become_user: root
  shell: "{{ upsource_install_dir }}/bin/upsource.sh stop"
  tags:
    - upsource

- name: "UpSource | Service | Start"
  become: yes
  become_user: root
  shell: "{{ upsource_install_dir }}/bin/upsource.sh start"
  tags:
    - upsource