---

- name: "UpSource | Get distribution"
  get_url:
    url: "http://download.jetbrains.com/upsource/upsource-{{ upsource_version }}.zip"
    dest: "/tmp/upsource-{{ upsource_version }}.zip"
    validate_certs: no
  tags:
    - upsource

- name: "UpSource | Unpack distribution"
  become: yes
  become_user: root
  unarchive:
    src: "/tmp/upsource-{{ upsource_version }}.zip"
    dest: "{{ upsource_install_dir }}"
    copy: "no"
  tags:
    - upsource

- name: "UpSource | Move distribution"
  become: yes
  become_user: root
  synchronize:
    src: "{{ upsource_install_dir }}/upsource-{{ upsource_version }}/"
    dest: "{{ upsource_install_dir }}/"
    recursive: yes
    delete: yes

- name: "UpSource | Ensure directory is writable"
  become: yes
  become_user: root
  file:
    path: "{{ upsource_install_dir }}"
    state: directory
    owner: "{{ fubarhouse_user }}"
    group: "{{ fubarhouse_user }}"
    mode: 0755
    recurse: true

- name: "UpSource | Remove superseded folder"
  become: yes
  become_user: root
  file:
    path: "{{ upsource_install_dir }}/upsource-{{ upsource_version }}"
    state: absent

- name: "Upsource | Configure to run on desired port"
  become: yes
  become_user: root
  shell: "{{ upsource_install_dir }}/bin/upsource.sh configure --listen-port {{ upsource_port }} --base-url http://servername:{{ upsource_port }}/"