---

- name: "UpSource | Service | Stop"
  shell: "{{ upsource_install_dir }}/bin/upsource.sh stop"
  when: '"Upsource is running" in upsource_service_status'
  tags:
    - upsource

- name: "UpSource | Uninstall"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ upsource_install_dir }}"